package br.inatel.yugioh.view;

import br.inatel.yugioh.control.Deck;
import br.inatel.yugioh.model.*;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Samuel
 */
public class CadastroMagica extends javax.swing.JFrame {

    private Deck d = new Deck();
    private ArrayList<Carta> dck = new ArrayList<>();

    /**
     * Creates new form CadastroMagica
     */
    public CadastroMagica() {
        initComponents();
        this.setLocationRelativeTo(null);           // Centralizar a Tela
        dck = d.lerDeck();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_icone = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        lbl_efeito = new javax.swing.JLabel();
        lbl_iconeDesc = new javax.swing.JLabel();
        lbl_nome = new javax.swing.JLabel();
        lbl_Carta = new javax.swing.JLabel();
        lbl_img = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        nome = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        tipo = new javax.swing.JLabel();
        icone = new javax.swing.JLabel();
        desc = new javax.swing.JLabel();
        scr_efeito = new javax.swing.JScrollPane();
        txt_desc = new javax.swing.JTextArea();
        btn_img = new javax.swing.JButton();
        id = new javax.swing.JLabel();
        txt_ID = new javax.swing.JTextField();
        combo_icone = new javax.swing.JComboBox<>();
        combo_tipo = new javax.swing.JComboBox<>();
        btn_ok = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        lbl_Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_icone.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(lbl_icone, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 30, 30));

        lbl_id.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_id.setToolTipText("");
        lbl_id.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(lbl_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 30, 10));

        lbl_efeito.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(lbl_efeito, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 260, 80));

        lbl_iconeDesc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_iconeDesc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_iconeDesc.setToolTipText("");
        jPanel1.add(lbl_iconeDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 74, 240, 40));

        lbl_nome.setFont(new java.awt.Font("Dialog", 1, 21)); // NOI18N
        lbl_nome.setToolTipText("");
        jPanel1.add(lbl_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 220, 40));

        lbl_Carta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/inatel/yugioh/img/card/magicPNG.png"))); // NOI18N
        jPanel1.add(lbl_Carta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        jPanel1.add(lbl_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 250, 250));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setOpaque(false);

        nome.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nome.setText("Nome");

        txt_nome.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txt_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomeActionPerformed(evt);
            }
        });

        tipo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tipo.setText("Tipo");

        icone.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        icone.setText("Icone");

        desc.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        desc.setText("Efeito");

        txt_desc.setColumns(20);
        txt_desc.setRows(5);
        scr_efeito.setViewportView(txt_desc);

        btn_img.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_img.setText("Selecionar Imagem");
        btn_img.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imgActionPerformed(evt);
            }
        });

        id.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        id.setText("ID");

        txt_ID.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IDActionPerformed(evt);
            }
        });

        combo_icone.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        combo_icone.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Equipamento", "Ritual", "Campo", "Contínuo", "Rápida", "Resposta" }));
        combo_icone.setSelectedIndex(-1);
        combo_icone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_iconeActionPerformed(evt);
            }
        });

        combo_tipo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        combo_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mágica", "Armadilha" }));
        combo_tipo.setSelectedIndex(-1);
        combo_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_tipoActionPerformed(evt);
            }
        });

        btn_ok.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_ok.setText("OK");
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });

        btn_cancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_cancel.setText("Cancelar");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_img)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_cancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_ok))
                    .addComponent(scr_efeito)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(icone)
                                    .addComponent(tipo)
                                    .addComponent(id))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(combo_icone, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(combo_tipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(desc))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(icone)
                    .addComponent(combo_icone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipo)
                    .addComponent(combo_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id)
                    .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(desc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scr_efeito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_img)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_ok)
                        .addComponent(btn_cancel)))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 390, 480));

        lbl_Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/inatel/yugioh/img/wallpaper_35.png"))); // NOI18N
        jPanel1.add(lbl_Fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomeActionPerformed

    }//GEN-LAST:event_txt_nomeActionPerformed

    private void btn_imgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imgActionPerformed
        escolherImagem();       // Selecionar Imagem da Carta
    }//GEN-LAST:event_btn_imgActionPerformed

    private void txt_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IDActionPerformed

    }//GEN-LAST:event_txt_IDActionPerformed

    private void combo_iconeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_iconeActionPerformed
        setarIcone();   // Equipamento, ritual, continua, etc
    }//GEN-LAST:event_combo_iconeActionPerformed

    private void combo_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_tipoActionPerformed
        setarTipoCarta();   // Tipo da carta (Magic ou TRap)
    }//GEN-LAST:event_combo_tipoActionPerformed

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        botaoOK();          // botão OK
    }//GEN-LAST:event_btn_okActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroMagica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroMagica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroMagica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroMagica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroMagica().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_img;
    private javax.swing.JButton btn_ok;
    private javax.swing.JComboBox<String> combo_icone;
    private javax.swing.JComboBox<String> combo_tipo;
    private javax.swing.JLabel desc;
    private javax.swing.JLabel icone;
    private javax.swing.JLabel id;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_Carta;
    private javax.swing.JLabel lbl_Fundo;
    private javax.swing.JLabel lbl_efeito;
    private javax.swing.JLabel lbl_icone;
    private javax.swing.JLabel lbl_iconeDesc;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_img;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel nome;
    private javax.swing.JScrollPane scr_efeito;
    private javax.swing.JLabel tipo;
    private javax.swing.JTextField txt_ID;
    private javax.swing.JTextArea txt_desc;
    private javax.swing.JTextField txt_nome;
    // End of variables declaration//GEN-END:variables

    private void preencherDados() {
        // Nome
        lbl_nome.setText(txt_nome.getText());
        // Efeito
        lbl_efeito.setText(txt_desc.getText());
        // ID
        lbl_id.setText(txt_ID.getText());
    }

    private void botaoOK() {
        salvar();
    }

    private void salvar() {

        // Verifica se todos os dados foram preenchidos
        if (!txt_ID.getText().equals("")
                && !txt_desc.getText().equals("")
                && !txt_nome.getText().equals("")) {

            // Salva as informações
            CartaMagica c = new CartaMagica();

            c.setDescricao(scr_efeito.getToolTipText());
            c.setAtributo(combo_tipo.getSelectedItem() + "");
            c.setID(txt_ID.getText());
            c.setNome(txt_nome.getText());
            c.seteMonstro(false);
            c.setIcone(combo_icone.getSelectedItem() + "");
            c.setTipo(combo_tipo.getSelectedItem() + "");
            c.setImg(lbl_img.getIcon());

            dck.add(c);
            d.salvarDeck(dck);

            JOptionPane.showMessageDialog(rootPane, "Carta Magica Cadastrada com Sucesso!");

            // Sai da tela e volta pro menu
            Menu menu = new Menu();
            menu.setVisible(true);
            this.dispose();
        }
    }

    public void limparDados() {
        txt_ID.setText("");
        txt_desc.setText("");
        txt_nome.setText("");
    }

    private void setarIcone() {
        ImageIcon continuous = new ImageIcon("src\\br\\inatel\\yugioh\\img\\type\\type_continuous.png");
        ImageIcon counter = new ImageIcon("src\\br\\inatel\\yugioh\\img\\type\\type_counter.png");
        ImageIcon equip = new ImageIcon("src\\br\\inatel\\yugioh\\img\\type\\type_equip.png");
        ImageIcon field = new ImageIcon("src\\br\\inatel\\yugioh\\img\\type\\type_field.png");
        ImageIcon quickPlay = new ImageIcon("src\\br\\inatel\\yugioh\\img\\type\\type_quickPlay.png");
        ImageIcon ritual = new ImageIcon("src\\br\\inatel\\yugioh\\img\\type\\type_ritual.png");

        if (combo_icone.getSelectedItem().equals("Ritual")) {
            lbl_icone.setIcon(ritual);
        }
        if (combo_icone.getSelectedItem().equals("Contínuo")) {
            lbl_icone.setIcon(continuous);
        }
        if (combo_icone.getSelectedItem().equals("Equipamento")) {
            lbl_icone.setIcon(equip);
        }
        if (combo_icone.getSelectedItem().equals("Campo")) {
            lbl_icone.setIcon(field);
        }
        if (combo_icone.getSelectedItem().equals("Rápida")) {
            lbl_icone.setIcon(quickPlay);
        }
        if (combo_icone.getSelectedItem().equals("Resposta")) {
            lbl_icone.setIcon(counter);
        }
        if (combo_icone.getSelectedItem().equals("Normal")) {
            lbl_icone.setIcon(null);
            if (combo_tipo.getSelectedItem() != null) {
                if (combo_tipo.getSelectedItem().equals("Mágica")) {
                    lbl_iconeDesc.setText("[Spell Card]");
                } else {
                    lbl_iconeDesc.setText("[Trap Card]");
                }
            }

        }
    }

    private void escolherImagem() {
        JFileChooser file = new JFileChooser();
        file.setFileSelectionMode(JFileChooser.FILES_ONLY);

        File dir = new File("src\\br\\inatel\\yugioh\\content");
        file.setCurrentDirectory(dir);

        int i = file.showSaveDialog(null);
        if (i == 1) {
            lbl_img.setText("");
        } else {
            File arquivo = file.getSelectedFile();
            ImageIcon img = new ImageIcon(arquivo.getAbsolutePath());
            lbl_img.setIcon(img);
            preencherDados();
        }
    }

    private void setarTipoCarta() {
        ImageIcon magic = new ImageIcon("src\\br\\inatel\\yugioh\\img\\card\\magicPNG.png");
        ImageIcon trap = new ImageIcon("src\\br\\inatel\\yugioh\\img\\card\\trapPNG.png");

        if (combo_tipo.getSelectedItem() != null) {
            if (combo_tipo.getSelectedItem().equals("Mágica")) {
                lbl_Carta.setIcon(magic);
                lbl_iconeDesc.setText("[Spell Card      ]");
            }
            if (combo_tipo.getSelectedItem().equals("Armadilha")) {
                lbl_Carta.setIcon(trap);
                lbl_iconeDesc.setText("[Trap Card      ]");
            }
        }

    }

}
